train:
  data_path: "/userfiles/ssafadoust20/expert_data"
  num_epochs: 20
  batch_size: 128
  lr: 0.0002
  weight_decay: 0.001
  num_workers: 10
  optimizer: "Adam"
  use_wandb: False
  

wandb:
  project: "CVAD"
  name: "part2-affordance-1-out"
